
apps:
  dir: &apps_dir ./apps
  default: home

server:
  host: 0.0.0.0
  port: 25842
  session:
    secret: "these are not the droids you are looking for"

storage:
  global:
    adapter: 'nedbDOWN'
    dir: data
  plugins:
    adapter: 'nedbDOWN'
    dir: data/plugins
  apps:
    adapter: 'nedbDOWN'
    dir: *apps_dir

log:
  exitOnError: true
  transports:
    - type: 'Console'
      options:
        timestamp: true
        colorize: true
    - type: 'File'
      options:
        filename: data/snap.log
        maxsize: 30000000
        maxFiles: 1
        handleExceptions: true