
apps:
  dir: &apps_dir ./apps
  default: home

server:
  host: 0.0.0.0
  port: 25842
  session:
    secret: "these are not the droids you are looking for"
    resave: false
    saveUninitialized: false
  primus:
    transformer: faye

storage:
  global:
    adapter: 'nedbDOWN'
    dir: data
  plugins:
    adapter: 'nedbDOWN'
    dir: data/plugins
  apps:
    adapter: 'nedbDOWN'
    dir: *apps_dir

log:
  level: info

theme: ~ # The path to the theme
