
apps:
  dir: ./apps
  default: home

server:
  host: 0.0.0.0
  port: 25842
  session:
    secret: "these are not the droids you are looking for"

window:
  position: center
  toolbar: False

data:
  dir: ./data
  autoCreate: True
  inMemoryOnly: False