
apps:
  dir: &apps_dir ./apps
  default: home

server:
  host: 0.0.0.0
  port: 25842
  session:
    secret: "these are not the droids you are looking for"

storage:
  global:
    memory: false
    dir: ./data
  plugins:
    memory: false
    dir: ./data/plugins
  apps:
    memory: false
    dir: *apps_dir